jobs:
  test-fedora-33:
    runs-on: ubuntu-latest
    steps:
      - name: Run in LXC (Fedora 33)
        uses: wsdfhjxc/run-in-lxc-action@1.x
        with:
          distr: fedora
          release: 33
          run: |
            echo "Testing"
            ./scripts/test.sh